"""Render a demo result as a self-contained static HTML page (no external deps).

Shows the model, request shape, cost statistics, the selected candidate, candidate-cost bars, and the
chosen first action vector — the "minimal UI" from RFC-0005 / issue #6.
"""

from __future__ import annotations

import html
from pathlib import Path
from typing import Any


def _tensor_data(node: Any) -> Any:
    """Pull inline data out of a TensorRef-or-list output node (None if URI-backed)."""
    if isinstance(node, dict):
        return node.get("data")
    return node


def _first_row(node: Any) -> list[float]:
    data = _tensor_data(node)
    if isinstance(data, list) and data and isinstance(data[0], list):
        return [float(x) for x in data[0]]
    if isinstance(data, list):
        return [float(x) for x in data]
    return []


def _bars(costs: list[float], best_index: int) -> str:
    if not costs:
        return '<p class="muted">candidate costs not inline (URI-backed)</p>'
    lo, hi = min(costs), max(costs)
    span = (hi - lo) or 1.0
    rows = []
    for i, c in enumerate(costs):
        pct = 8 + 92 * (c - lo) / span
        cls = "bar best" if i == best_index else "bar"
        rows.append(
            f'<div class="barrow"><span class="idx">{i}</span>'
            f'<span class="{cls}" style="width:{pct:.1f}%"></span>'
            f'<span class="val">{c:.4f}</span></div>'
        )
    return "\n".join(rows)


def summarize_html(result: dict[str, Any]) -> str:
    meta = result.get("metadata", {})
    score_out = result.get("score", {}).get("outputs", {})
    plan_out = result.get("plan", {}).get("outputs", {})
    shape = result.get("request_shape", {})

    costs = _first_row(score_out.get("costs"))
    best_index_list = score_out.get("best_index") or [0]
    best_index = int(best_index_list[0]) if best_index_list else 0
    stats = score_out.get("cost_statistics", {})
    best_cost_list = plan_out.get("best_cost") or []
    best_cost = best_cost_list[0] if best_cost_list else None
    first_action = _first_row(plan_out.get("first_action"))

    model_id = html.escape(str(meta.get("model_id", "lewm-pusht")))
    revision = html.escape(str(meta.get("model_revision", "?")))
    backend = html.escape(str(meta.get("runtime", {}).get("backend", "?")))
    stat_line = " · ".join(f"{k}={v:.4f}" for k, v in stats.items() if isinstance(v, (int, float)))
    action_str = ", ".join(f"{x:+.3f}" for x in first_action) or "(URI-backed)"

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>WMCP Push-T demo</title>
<style>
  :root {{ color-scheme: dark; }}
  body {{ font: 15px/1.5 ui-monospace, SFMono-Regular, Menlo, monospace; background:#0b0e14; color:#c9d1d9; margin:0; padding:2rem; }}
  .wrap {{ max-width: 760px; margin: 0 auto; }}
  h1 {{ font-size: 1.25rem; letter-spacing:.02em; }}
  .tag {{ color:#58a6ff; }}
  .card {{ background:#11151c; border:1px solid #222a35; border-radius:10px; padding:1rem 1.25rem; margin:1rem 0; }}
  .grid {{ display:grid; grid-template-columns:auto 1fr; gap:.25rem 1rem; }}
  .muted {{ color:#6e7681; }}
  .k {{ color:#8b949e; }}
  .v {{ color:#e6edf3; }}
  .barrow {{ display:grid; grid-template-columns:2.2rem 1fr 4.5rem; align-items:center; gap:.5rem; margin:.15rem 0; }}
  .bar {{ height:.7rem; background:#30425f; border-radius:3px; }}
  .bar.best {{ background:#3fb950; }}
  .idx {{ color:#6e7681; text-align:right; }}
  .val {{ color:#8b949e; text-align:right; }}
  .pill {{ display:inline-block; background:#16203a; color:#58a6ff; padding:.1rem .5rem; border-radius:999px; }}
</style></head>
<body><div class="wrap">
  <h1>WMCP <span class="tag">Push-T</span> demo result</h1>
  <div class="card"><div class="grid">
    <span class="k">model</span><span class="v">{model_id} <span class="muted">(rev {revision}, backend {backend})</span></span>
    <span class="k">score shape</span><span class="v">B=1 · S={shape.get('S', '?')} · T={shape.get('T', '?')}</span>
    <span class="k">cost stats</span><span class="v">{html.escape(stat_line) or '—'}</span>
  </div></div>
  <div class="card">
    <div class="grid">
      <span class="k">best candidate</span><span class="v"><span class="pill">#{best_index}</span></span>
      <span class="k">plan best_cost</span><span class="v">{'%.4f' % best_cost if isinstance(best_cost, (int, float)) else '—'}</span>
      <span class="k">first action</span><span class="v">[{html.escape(action_str)}]</span>
    </div>
  </div>
  <div class="card">
    <div class="k" style="margin-bottom:.5rem">candidate costs (green = chosen)</div>
    {_bars(costs, best_index)}
  </div>
  <p class="muted">Generated by <code>python -m client.demo</code> against the WMCP inference service.</p>
</div></body></html>
"""


def render_html(result: dict[str, Any], path: str | Path) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(summarize_html(result), encoding="utf-8")
    return target
